# Generated by Django 4.2.4 on 2023-09-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_profile_full_name_customuser_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(default=1693718750.54935, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
