# Generated by Django 4.1 on 2023-09-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_customuser_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.ForeignKey(
                default=1694614213.704938,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
