# Generated by Django 4.2.4 on 2023-09-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_profile_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(default=1694691730.729724, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
