# Generated by Django 4.1 on 2023-09-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_customuser_profile_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(default=1694710554.90963, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
