# Generated by Django 4.2.5 on 2023-09-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_friend_unique_together_friend_user_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.ForeignKey(
                default=1694790531.674277,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
