# Generated by Django 4.1 on 2023-09-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(default=1695003231.769963, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
